spring:
  profiles:
    group:
      default: common, local
      dev: common, dev
      stg: common, stg
      prd: common, prd
    active: default

---

spring:
  config:
    activate:
      on-profile: common

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
