spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: yongwoo
    password: yongwoo
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: true