@Reference : https://otrodevym.tistory.com/m/entry/intellij-인텔리제이-http로-postman-대체하는-방법
@Description
  첫번째 줄 : [Http Method] URL
  두번째 줄 : Request Header
  세번째 줄 : 공백
  네번째 줄 : Request Body
    - < : RequestBody로 .json 파일 사용 (< ./Spring.json)
    - > : response 결과 파일을 사용

  # IntelliJ 에선 Controller 함수에서 "Run HTTP Request"를 통해 바로 생성할 수 있다.
  # 동적 변수
    $$uuid: UUID
    $$timestamp: Unix Timestamp
    $$randomInt: 0에서 1000 사이의 랜덤 숫자
  # 환경변수
    http-client.env.json
    http-client.private.env.json


###
GET localhost:8080/health
Content-Type: application/json
Authorization: token
Cookie: user=userCookie

"Hello"

###
POST  localhost:8080/health
Content-Type: application/json

< ./json/Spring.json
> {% response.status %}


###
POST localhost:8080/health
Content-Type: application/json

{
  "name": "beaver"
}