spring:
  config:
    activate:
      on-profile: local
  flyway:
    locations: classpath:/db/migration/common, classpath:/db/migration/env/local
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        # Hibernate가 출력하는 SQL 쿼리가 보다 가독성이 좋은 형태로 출력
  rest-template:
    connection-timeout: 5000
    read-timeout: 5000
    max-connection: 100
    max-per-route: 50
  redis:
    host: localhost
    port: 6379
    ttl: 1000
  ### Mysql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
    username: yongwoo
    password: yongwoo
### H2
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:search;MODE=MySQL
#    username: yongwoo
#    password: yongwoo
#  h2:
#    console:
#      enabled: true
api:
  kakao:
    token: temp # Change to value you want!
    host: https://dapi.kakao.com
    url:
      blog: /v2/search/blog
      image: /v2/search/image
  naver:
    client-id: temp # Change to value you want!
    client-secret: temp # Change to value you want!
    host: https://openapi.naver.com
    url:
      blog: /v1/search/blog
      image: /v1/search/image
logging:
  level:
    root: info