version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
      MYSQL_USER: yongwoo
      MYSQL_PASSWORD: yongwoo
