spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3330/spring
    username: root
    password: yongwoo
  flyway:
    url: jdbc:mysql://localhost:3330/spring?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    schema: spring
    user: root
    password: yongwoo
    locations: classpath:/db/migration
    out-of-order: true
#  redis:
#    host:
#    port:
#    session-ttl:

cloud:

logging:
  level:
    modern: info