apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  selector:
    matchLabels:
      app: counter
      tier: app
  template:
    metadata:
      labels:
        app: counter
        tier: app
    spec:
      containers:
      - name: counter
        image: ghcr.io/subicura/counter:latest
        env:
        - name: REDIS_HOST
          value: "redis"  # 위에서 만든 Service 이름
        - name: REDIS_PORT
          value: "6379"
