spring:
  config:
    activate:
      on-profile: stg
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:search;MODE=MySQL
    username: temp # Change to value you want!
    password: temp # Change to value you want!
  flyway:
    locations: classpath:/db/migration/common, classpath:/db/migration/env/stg
    out-of-order: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  rest-template:
    connection-timeout: 5000
    read-timeout: 5000
    max-connection: 100
    max-per-route: 50
  h2:
    console:
      enabled: true
api:
  kakao:
    token: temp # Change to value you want!
    host: https://dapi.kakao.com
    url:
      blog: /v2/search/blog
      image: /v2/search/image
  naver:
    client-id: temp # Change to value you want!
    client-secret: temp # Change to value you want!
    host: https://openapi.naver.com
    url:
      blog: /v1/search/blog
      image: /v1/search/image
logging:
  level:
    root: info